stages:
  make_dataset:
    cmd: python src/data/make_dataset.py
    deps:
    - data/raw
    - src/data/make_dataset.py
    outs:
    - data/processed
  data_preprocessing:
    cmd: python src/data/data_preprocessing.py
    deps:
    - data/processed
    - src/data/data_preprocessing.py
    outs:
    - data/interim
  train_model:
    cmd: python src/models/train_model.py
    deps:
    - data/interim
    - src/models/train_model.py
    outs:
    - models/pipeline
  evaluate_model:
    cmd: python src/models/evaluate_model.py
    deps:
      - src/models/evaluate_model.py
      - models/pipeline/pipeline_model.joblib
      - data/interim/test_with_predictions.csv
    outs:
      - models/metrics